name: Run Python Scraper

on:
  push:
    branches: [ main ]
  # schedule:
  #   - cron: '0 1 * * *'  # 每天 UTC 時間 1 點 (台灣時間早上 9 點) 執行

jobs:
  scrape_news:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run main.py
      run: python main.py