name: Run Python Scraper

on:
  push:
    branches: [ main ]

jobs:
  scrape_news:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run main.py and output to summary
      run: |
        echo "### Hacker News Headlines:" >> $GITHUB_STEP_SUMMARY
        python main.py >> $GITHUB_STEP_SUMMARY